#!/bin/bash
# Generate audio files using Google Cloud Text-to-Speech
# Prerequisites: gcloud CLI installed and authenticated
# gcloud auth application-default login
#
set -e

echo "Generating: assets/audio/intro_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أَبْطَالٌ فِي الظِّلِّ. سِيَرُ الجُنُودِ المَجْهُولِينَ مِنْ صَحَابَةِ رَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/intro_0.mp3"

echo "Generating: assets/audio/intro_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>حِينَ يَلْتَفِتُ التَّارِيخُ لِيُسَجِّلَ أَعْظَمَ التَّحَوُّلَاتِ، تَقْفِزُ إِلَى الأَذْهَانِ أَسْمَاءُ النُّجُومِ الكِبَارِ. لَكِنْ خَلْفَ هَذَا الوَمِيضِ، كَانَ هُنَاكَ جِيلٌ آخَرُ آثَرَ العَطَاءَ بِصَمْتٍ. هَؤُلَاءِ هُمُ الجُنُودُ المَجْهُولُونَ، صَحَابَةٌ كِرَامٌ نُقِشَتْ أَسْمَاؤُهُمْ بِأَحْرُفٍ مِنْ نُورٍ فِي دِيوَانِ السَّمَاءِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/intro_1.mp3"

echo "Generating: assets/audio/intro_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ هَذَا المَشْرُوعِ: العَطَاءُ لِلدِّينِ لَا يَحْتَاجُ إِلَى أَضْوَاءٍ وَلَا إِلَى شَهْرَةٍ. وَاللهُ يُحِبُّ العَبْدَ التَّقِيَّ النَّقِيَّ الخَفِيَّ. وَكُلُّ مُسْلِمٍ يَمْلِكُ تَخَصُّصًا يُمْكِنُهُ تَقْدِيمُهُ خِدْمَةً لِدِينِهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/intro_2.mp3"

echo "Generating: assets/audio/intro_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>هَذِهِ قِصَصُ ثَمَانِيَةٍ مِنَ الجُنُودِ المَجْهُولِينَ. اخْتَرْ بِطَلَكَ وَابْدَأِ الرِّحْلَةَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/intro_3.mp3"

echo "Generating: assets/audio/hubab_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>الحُبَابُ بْنُ المُنْذِرِ. مُهَنْدِسُ النَّصْرِ وَمُسْتَشَارُ بَدْرٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/hubab_0.mp3"

echo "Generating: assets/audio/hubab_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ سَادَةِ الخَزْرَجِ الأَنْصَارِ، لُقِّبَ بِـذِي الرَّأْيِ لِسَدَادِ رَأْيِهِ وَحُسْنِ تَدْبِيرِهِ. شَهِدَ بَدْرًا وَجَمِيعَ المَشَاهِدِ مَعَ رَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/hubab_1.mp3"

echo "Generating: assets/audio/hubab_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>فِي غَزْوَةِ بَدْرٍ الكُبْرَى عَامَ اثْنَيْنِ مِنَ الهِجْرَةِ، نَزَلَ الجَيْشُ عِنْدَ أَوَّلِ بِئْرٍ. وَنَظَرَ الحُبَابُ بِعَيْنِ الخَبِيرِ فَرَأَى خَطَرًا دَاهِمًا.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/hubab_2.mp3"

echo "Generating: assets/audio/hubab_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>تَقَدَّمَ الحُبَابُ إِلَى النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ بِأَدَبٍ وَسَأَلَ: يَا رَسُولَ اللهِ، أَرَأَيْتَ هَذَا المَنْزِلَ؟ أَهُوَ مَنْزِلٌ أَنْزَلَكَهُ اللهُ فَلَيْسَ لَنَا أَنْ نَتَقَدَّمَهُ وَلَا نَتَأَخَّرَ عَنْهُ؟ أَمْ هُوَ الرَّأْيُ وَالحَرْبُ وَالمَكِيدَةُ؟ فَقَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: بَلْ هُوَ الرَّأْيُ وَالحَرْبُ وَالمَكِيدَةُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/hubab_3.mp3"

echo "Generating: assets/audio/hubab_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ الحُبَابُ: نَنْزِلُ أَدْنَى مَاءٍ مِنَ القَوْمِ، وَنُغَوِّرُ مَا وَرَاءَهُ مِنَ الأَبَارِ، وَنَبْنِي حَوْضًا فَنَشْرَبُ وَلَا يَشْرَبُونَ! فَقَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: لَقَدْ أَشَرْتَ بِالرَّأْيِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/hubab_4.mp3"

echo "Generating: assets/audio/hubab_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ قِصَّةِ الحُبَابِ: قَدِّمْ تَخَصُّصَكَ لِدِينِكَ، فَالحُبَابُ عَرَفَ الآبَارَ فَقَدَّمَ خِبْرَتَهُ لِلإِسْلَامِ. وَأَدَبُ السُّؤَالِ قَبْلَ الكَلَامِ. وَالشُّورَى الحَقِيقِيَّةُ أَنَّ النَّبِيَّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ قَبِلَ رَأْيَ جُنْدِيٍّ وَغَيَّرَ خُطَّةَ المَعْرَكَةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/hubab_5.mp3"

echo "Generating: assets/audio/hubab_6.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>رَحَلَ الحُبَابُ بْنُ المُنْذِرِ وَلَمْ يَتْرُكْ خَلْفَهُ آلَافَ الأَحَادِيثِ. لَكِنَّهُ تَرَكَ بِئْرًا وَاحِدَةً غَيَّرَتْ مَوَازِينَ بَدْرٍ. فَرَضِيَ اللهُ عَنِ الحُبَابِ بْنِ المُنْذِرِ، جُنْدِيٌّ وَاحِدٌ بِرَأْيٍ صَادِقٍ صَنَعَ النَّصْرَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/hubab_6.mp3"

echo "Generating: assets/audio/nuaym_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>نُعَيْمُ بْنُ مَسْعُودٍ. الرَّجُلُ الَّذِي هَزَمَ جُيُوشَ الأَحْزَابِ بِمُفْرَدِهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/nuaym_0.mp3"

echo "Generating: assets/audio/nuaym_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>كَانَ نُعَيْمُ بْنُ مَسْعُودٍ دَاهِيَةً مِنْ دَوَاهِي العَرَبِ، صَاحِبَ شَبَكَةِ عَلَاقَاتٍ وَاسِعَةٍ. وَأَسْلَمَ سِرًّا أَثْنَاءَ حِصَارِ الخَنْدَقِ عَامَ خَمْسَةٍ مِنَ الهِجْرَةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/nuaym_1.mp3"

echo "Generating: assets/audio/nuaym_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>تَسَلَّلَ نُعَيْمٌ إِلَى المَدِينَةِ سِرًّا وَأَعْلَنَ إِسْلَامَهُ لِلنَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَقَالَ: يَا رَسُولَ اللهِ، مُرْنِي بِمَا شِئْتَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/nuaym_2.mp3"

echo "Generating: assets/audio/nuaym_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ لَهُ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: إِنَّمَا أَنْتَ فِينَا رَجُلٌ وَاحِدٌ، فَخَذِّلْ عَنَّا إِنِ اسْتَطَعْتَ، فَإِنَّ الحَرْبَ خُدْعَةٌ. فَانْطَلَقَ نُعَيْمٌ يُنَفِّذُ أَعْقَدَ عَمَلِيَّةِ تَفْتِيتٍ نَفْسِيٍّ فِي التَّارِيخِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/nuaym_3.mp3"

echo "Generating: assets/audio/nuaym_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>ذَهَبَ نُعَيْمٌ إِلَى بَنِي قُرَيْظَةَ فَأَلْقَى فِي قُلُوبِهِمُ الشَّكَّ، ثُمَّ إِلَى قُرَيْشٍ وَغَطَفَانَ فَبَثَّ الرِّيبَةَ بَيْنَهُمَا. فَانْفَرَطَ عِقْدُ التَّحَالُفِ وَانْكَسَرَ الحِصَارُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/nuaym_4.mp3"

echo "Generating: assets/audio/nuaym_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ قِصَّةِ نُعَيْمٍ: قِيمَةُ الفَرْدِ، فَرَجُلٌ وَاحِدٌ مُخْلِصٌ يُمْكِنُهُ تَعْدِيلُ كَفَّةِ الصِّرَاعِ. وَتَوْظِيفُ القُدْرَاتِ، فَالنَّبِيُّ وَجَّهَ نُعَيْمًا بِحَسَبِ مَوْهِبَتِهِ. وَسُرْعَةُ العَطَاءِ بَعْدَ الهِدَايَةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/nuaym_5.mp3"

echo "Generating: assets/audio/nuaym_6.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>خَرَجَ نُعَيْمٌ رَجُلًا وَاحِدًا وَعَادَ وَقَدْ فَكَّكَ جَيْشًا مِنْ عَشَرَةِ آلَافٍ. فَرَضِيَ اللهُ عَنْ نُعَيْمِ بْنِ مَسْعُودٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/nuaym_6.mp3"

echo "Generating: assets/audio/rabia_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>رَبِيعَةُ بْنُ كَعْبٍ الأَسْلَمِيُّ. الشَّابُّ الَّذِي اشْتَرَى الفِرْدَوْسَ بِإِنَاءِ وُضُوءٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/rabia_0.mp3"

echo "Generating: assets/audio/rabia_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>فَتًى شَابٌّ مِنَ الصُّفَّةِ، لَا بَيْتَ لَهُ وَلَا مَالَ. نَذَرَ حَيَاتَهُ وَشَبَابَهُ لِيَكُونَ ظِلًّا لِرَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ يَخْدُمُهُ فِي حِلِّهِ وَتَرْحَالِهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/rabia_1.mp3"

echo "Generating: assets/audio/rabia_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>كَانَ رَبِيعَةُ يُلَازِمُ عَتَبَةَ بَيْتِ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ طَوَالَ اللَّيْلِ. فَإِذَا اسْتَيْقَظَ النَّبِيُّ وَجَدَهُ وَاقِفًا بِالمَاءِ يَنْتَظِرُ بِصَمْتٍ وَوَفَاءٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/rabia_2.mp3"

echo "Generating: assets/audio/rabia_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ لَهُ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: سَلْنِي مَا شِئْتَ. فَقَالَ رَبِيعَةُ: أَسْأَلُكَ مُرَافَقَتَكَ فِي الجَنَّةِ! فَقَالَ النَّبِيُّ: فَأَعِنِّي عَلَى نَفْسِكَ بِكَثْرَةِ السُّجُودِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/rabia_3.mp3"

echo "Generating: assets/audio/rabia_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ رَبِيعَةَ: الهِمَّةُ لَا تُقَيِّدُهَا الظُّرُوفُ، فَالفَقْرُ لَا يَمْنَعُ الطُّمُوحَ. وَالعَمَلُ مَقْرُونٌ بِالأَمَلِ، فَالأُمْنِيَاتُ تَحْتَاجُ إِلَى سُجُودٍ. وَشَرَفُ الخِدْمَةِ الصَّادِقَةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/rabia_4.mp3"

echo "Generating: assets/audio/rabia_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مَاتَ رَبِيعَةُ وَلَمْ يَتْرُكْ مَالًا، لَكِنَّهُ تَرَكَ لِكُلِّ سَاجِدٍ أَمَلًا. فَرَضِيَ اللهُ عَنْ رَبِيعَةَ بْنِ كَعْبٍ الأَسْلَمِيِّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/rabia_5.mp3"

echo "Generating: assets/audio/amr_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>عَمْرُو بْنُ الجَمُوحِ. الأَعْرَجُ الَّذِي طَارَ بِأَجْنِحَةِ الشَّهَادَةِ فِي أُحُدٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/amr_0.mp3"

echo "Generating: assets/audio/amr_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>سَيِّدٌ مِنْ سَادَاتِ بَنِي سَلِمَةَ، أَسْلَمَ فِي سِنٍّ مُتَأَخِّرَةٍ. كَانَ يُعَانِي مِنْ عَرَجٍ شَدِيدٍ فِي رِجْلِهِ، لَكِنَّ قَلْبَهُ لَمْ يَكُنْ فِيهِ عَرَجٌ قَطُّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/amr_1.mp3"

echo "Generating: assets/audio/amr_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>لَمَّا نُودِيَ لِغَزْوَةِ أُحُدٍ، مَنَعَهُ أَبْنَاؤُهُ الأَرْبَعَةُ قَائِلِينَ: إِنَّ اللهَ قَدْ عَذَرَكَ. فَغَضِبَ الشَّيْخُ وَقَرَّرَ أَنْ يَذْهَبَ إِلَى النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/amr_2.mp3"

echo "Generating: assets/audio/amr_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ عَمْرٌو: يَا رَسُولَ اللهِ، إِنَّ بَنِيَّ يُرِيدُونَ أَنْ يَحْبِسُونِي، وَاللهِ إِنِّي لَأَرْجُو أَنْ أَطَأَ بِعَرْجَتِي هَذِهِ الجَنَّةَ! فَقَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: مَا عَلَيْكُمْ أَلَّا تَمْنَعُوهُ، لَعَلَّ اللهَ أَنْ يَرْزُقَهُ الشَّهَادَةَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/amr_3.mp3"

echo "Generating: assets/audio/amr_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>نَزَلَ عَمْرٌو أَرْضَ المَعْرَكَةِ يُقَاتِلُ قِتَالَ الشَّبَابِ، وَكَانَ يَصِيحُ: وَا شَوْقَاهُ إِلَى الجَنَّةِ! وَا شَوْقَاهُ! حَتَّى اسْتُشْهِدَ رَضِيَ اللهُ عَنْهُ. وَقَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: كَأَنِّي أَنْظُرُ إِلَيْهِ يَطَأُ الجَنَّةَ بِعَرْجَتِهِ صَحِيحًا.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/amr_4.mp3"

echo "Generating: assets/audio/amr_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ عَمْرٍو: عُلُوُّ الهِمَّةِ فَالأَعْذَارُ الجَسَدِيَّةُ لَا تُقَيِّدُ القُلُوبَ الحَيَّةَ. وَالتَّعْوِيضُ الإِلَهِيُّ لِمَنْ تَرَكَ شَيْئًا لِلَّهِ. وَالنُّبُوَّةُ تَفْتَحُ بَابَ الأَمَلِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/amr_5.mp3"

echo "Generating: assets/audio/amr_6.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>سَقَطَ عَمْرُو بْنُ الجَمُوحِ بِعَرَجِهِ الدُّنْيَوِيِّ لِيَقُومَ بِخُطُوَاتٍ صَحِيحَةٍ فِي الجَنَّةِ. فَرَضِيَ اللهُ عَنْ عَمْرِو بْنِ الجَمُوحِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/amr_6.mp3"

echo "Generating: assets/audio/dhu_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>ذُو النِّجَادَيْنِ. الشَّابُّ الَّذِي دَفَنَهُ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ بِيَدِهِ الشَّرِيفَةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/dhu_0.mp3"

echo "Generating: assets/audio/dhu_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>شَابٌّ يَتِيمٌ مِنْ قَبِيلَةِ مُزَيْنَةَ، نَشَأَ فِي حِجْرِ عَمِّهِ الثَّرِيِّ. لَمَّا أَسْلَمَ، جَرَّدَهُ عَمُّهُ مِنْ كُلِّ شَيْءٍ، حَتَّى مِنَ الثَّوْبِ الَّذِي يَرْتَدِيهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/dhu_1.mp3"

echo "Generating: assets/audio/dhu_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَطَعَتْ أُمُّهُ بِجَادًا غَلِيظًا نِصْفَيْنِ، اتَّزَرَ بِنِصْفٍ وَارْتَدَى الآخَرَ، وَهَرَبَ لَيْلًا إِلَى المَدِينَةِ. فَلَمَّا وَصَلَ سَمَّاهُ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ ذَا النِّجَادَيْنِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/dhu_2.mp3"

echo "Generating: assets/audio/dhu_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>فِي غَزْوَةِ تَبُوكَ، أَصَابَتِ الحُمَّى ذَا النِّجَادَيْنِ فَمَاتَ. وَرَأَى ابْنُ مَسْعُودٍ فِي جَوْفِ اللَّيْلِ شَعْلَةً، فَإِذَا هُوَ رَسُولُ اللهِ وَأَبُو بَكْرٍ وَعُمَرُ يَحْفِرُونَ لَهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/dhu_3.mp3"

echo "Generating: assets/audio/dhu_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>وَقَفَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ فِي الحُفْرَةِ وَأَوْسَدَهُ بِيَدِهِ الشَّرِيفَةِ. ثُمَّ رَفَعَ يَدَيْهِ دَاعِيًا: اللَّهُمَّ إِنِّي أَمْسَيْتُ رَاضِيًا عَنْهُ فَارْضَ عَنْهُ. فَقَالَ ابْنُ مَسْعُودٍ رَضِيَ اللهُ عَنْهُ: يَا لَيْتَنِي كُنْتُ صَاحِبَ القَبْرِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/dhu_4.mp3"

echo "Generating: assets/audio/dhu_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ ذِي النِّجَادَيْنِ: التَّضْحِيَةُ بِالدُّنْيَا تِجَارَةٌ رَابِحَةٌ. وَمِقْيَاسُ التَّفَاضُلِ عِنْدَ اللهِ الصِّدْقُ وَالإِخْلَاصُ. وَوَفَاءُ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ لِكُلِّ جُنْدِيٍّ مُخْلِصٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/dhu_5.mp3"

echo "Generating: assets/audio/dhu_6.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>رَحَلَ ذُو النِّجَادَيْنِ بِكِسَائِهِ الخَشِنِ وَدُفِنَ بِدُعَاءِ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ. فَرَضِيَ اللهُ عَنْهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/dhu_6.mp3"

echo "Generating: assets/audio/julaybib_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>جُلَيْبِيبٌ. المَرْفُوعُ عَلَى سَاعِدَيِ النُّبُوَّةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/julaybib_0.mp3"

echo "Generating: assets/audio/julaybib_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>كَانَ رَجُلًا فَقِيرًا مِنْ أَهْلِ الصُّفَّةِ، دَمِيمَ الخِلْقَةِ يَبْتَعِدُ عَنْهُ النَّاسُ. لَكِنَّ النَّبِيَّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ كَانَ يُحِبُّهُ حُبًّا جَمًّا، وَزَوَّجَهُ بِبَرَكَةِ دُعَائِهِ الشَّرِيفِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/julaybib_1.mp3"

echo "Generating: assets/audio/julaybib_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: هَلْ تَفْقِدُونَ مِنْ أَحَدٍ؟ فَقَالُوا: نَفْقِدُ فُلَانًا وَفُلَانًا. فَقَالَ: لَكِنِّي أَفْقِدُ جُلَيْبِيبًا فَابْتَغُوهُ. فَوَجَدُوهُ صَرِيعًا وَحَوْلَهُ سَبْعَةٌ قَتَلَهُمْ ثُمَّ قُتِلَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/julaybib_2.mp3"

echo "Generating: assets/audio/julaybib_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: قَتَلَ سَبْعَةً ثُمَّ قَتَلُوهُ! هَذَا مِنِّي وَأَنَا مِنْهُ! ثُمَّ حَمَلَهُ عَلَى سَاعِدَيْهِ لِيَدْفِنَهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/julaybib_3.mp3"

echo "Generating: assets/audio/julaybib_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ جُلَيْبِيبٍ: اللهُ لَا يَنْظُرُ إِلَى الصُّوَرِ بَلْ إِلَى القُلُوبِ. وَرَعَايَةُ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ لِكُلِّ فَرْدٍ. وَالحُبُّ النَّبَوِيُّ لَا يُفَرِّقُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/julaybib_4.mp3"

echo "Generating: assets/audio/julaybib_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>رُفِعَ جُلَيْبِيبٌ عَلَى سَاعِدَيِ النُّبُوَّةِ وَنَالَ أَعْظَمَ وَسَامٍ: هَذَا مِنِّي وَأَنَا مِنْهُ. فَرَضِيَ اللهُ عَنْ جُلَيْبِيبٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/julaybib_5.mp3"

echo "Generating: assets/audio/silah_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>صِلَةُ بْنُ الحَارِثِ الغِفَارِيُّ. صَاحِبُ مُعْجِزَةِ الصَّحْرَاءِ وَالإِخْلَاصِ الخَفِيِّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/silah_0.mp3"

echo "Generating: assets/audio/silah_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>صَحَابِيٌّ مِنْ قَبِيلَةِ غِفَارَ، كَانَ كَتُومًا عَابِدًا مُجَاهِدًا بِصَمْتٍ فِي جُيُوشِ الفَتْحِ الإِسْلَامِيِّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/silah_1.mp3"

echo "Generating: assets/audio/silah_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>كَانَ صِلَةُ فِي جَيْشِ المُسْلِمِينَ فِي بِلَادِ الشَّامِ. فِي لَيْلَةٍ شَدِيدَةِ الظُّلْمَةِ وَالبَرْدِ، ضَلَّ الجَيْشُ وَنَفِدَ مَاؤُهُمْ وَكَادُوا يَهْلِكُونَ عَطَشًا.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/silah_2.mp3"

echo "Generating: assets/audio/silah_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>تَسَلَّلَ صِلَةُ سِرًّا وَابْتَعَدَ عَنِ المُعَسْكَرِ، فَسَجَدَ وَدَعَا اللهَ وَبَكَى. فَنَبَعَ المَاءُ مِنْ بَيْنِ يَدَيْهِ وَسْطَ الصَّحْرَاءِ القَاحِلَةِ! فَدَعَا الجَيْشَ فَشَرِبُوا وَسَقَوْا دَوَابَّهُمْ وَمَلَأُوا قِرَبَهُمْ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/silah_3.mp3"

echo "Generating: assets/audio/silah_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>ثُمَّ عَادَ صِلَةُ إِلَى صُفُوفِ الجَيْشِ صَامِتًا لَمْ يَقُلْ: أَنَا الَّذِي دَعَوْتُ، خَوْفًا مِنَ الرِّيَاءِ أَنْ يُفْسِدَ عَمَلَهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/silah_4.mp3"

echo "Generating: assets/audio/silah_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ قِصَّةِ صِلَةَ: أَوَّلًا، الإِخْلَاصُ الشَّدِيدُ وَالخَوْفُ مِنَ الشُّهْرَةِ، فَقَدْ نَصَرَ الجَيْشَ وَأَخْفَى المَشْهَدَ خَوْفًا مِنَ الرِّيَاءِ. وَثَانِيًا، اسْتِجَابَةُ الدُّعَاءِ لِلْمُضْطَرِّينَ فَالسُّجُودُ بِصِدْقٍ يَفْتَحُ أَبْوَابَ المُعْجِزَاتِ. وَهَذَا هُوَ التَّقِيُّ الخَفِيُّ الَّذِي يُحِبُّهُ اللهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/silah_5.mp3"

echo "Generating: assets/audio/silah_6.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>نَجَا الجَيْشُ بِدُعَاءِ رَجُلٍ لَمْ يَعْرِفْهُ أَحَدٌ. وَاللهُ يَعْلَمُ السِّرَّ وَأَخْفَى. فَرَضِيَ اللهُ عَنْ صِلَةَ بْنِ الحَارِثِ الغِفَارِيِّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/silah_6.mp3"

echo "Generating: assets/audio/abududahdah_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أَبُو الدَّحْدَاحِ. صَاحِبُ أَرْبَحِ بَيْعٍ فِي تَارِيخِ البَشَرِيَّةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abududahdah_0.mp3"

echo "Generating: assets/audio/abududahdah_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>ثَابِتُ بْنُ الدَّحْدَاحِ الأَنْصَارِيُّ، كَانَ يَمْلِكُ بُسْتَانًا عَظِيمًا فِي المَدِينَةِ فِيهِ نَخِيلٌ كَثِيرَةٌ وَبِئْرُ مَاءٍ وَقَصْرٌ تَعِيشُ فِيهِ أُسْرَتُهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abududahdah_1.mp3"

echo "Generating: assets/audio/abududahdah_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>لَمَّا نَزَلَتِ الآيَةُ: مَنْ ذَا الَّذِي يُقْرِضُ اللهَ قَرْضًا حَسَنًا، مَشَى أَبُو الدَّحْدَاحِ إِلَى النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ وَقَالَ: يَا رَسُولَ اللهِ، وَإِنَّ اللهَ يُرِيدُ مِنَّا القَرْضَ؟</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abududahdah_2.mp3"

echo "Generating: assets/audio/abududahdah_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ أَبُو الدَّحْدَاحِ: فَإِنِّي قَدْ أَقْرَضْتُ رَبِّي حَائِطِي. ثُمَّ ذَهَبَ إِلَى زَوْجَتِهِ أُمِّ الدَّحْدَاحِ وَنَادَاهَا: اخْرُجِي مِنَ الحَائِطِ، فَقَدْ بِعْتُهُ لِرَبِّي. فَقَالَتِ الزَّوْجَةُ الصَّالِحَةُ بِفَرَحٍ وَرِضًا: رَبِحَ البَيْعُ، رَبِحَ البَيْعُ. وَأَخْرَجَتِ التَّمْرَ مِنْ أَفْوَاهِ أَطْفَالِهَا.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abududahdah_3.mp3"

echo "Generating: assets/audio/abududahdah_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>وَلَمَّا مَشَى النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ فِي جَنَازَةِ أَبِي الدَّحْدَاحِ قَالَ: كَمْ مِنْ عِذْقٌ مُعَلَّقٌ لِأَبِي الدَّحْدَاحِ فِي الجَنَّةِ!</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abududahdah_4.mp3"

echo "Generating: assets/audio/abududahdah_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ أَبِي الدَّحْدَاحِ: الاسْتِجَابَةُ الفَوْرِيَّةُ لِلنَّصِّ الشَّرْعِيِّ. وَالزَّوْجَةُ الصَّالِحَةُ الَّتِي تُعِينُ زَوْجَهَا عَلَى الطَّاعَةِ. وَاليَقِينُ بِوَعْدِ اللهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abududahdah_5.mp3"

echo "Generating: assets/audio/abududahdah_6.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>بَاعَ أَبُو الدَّحْدَاحِ بُسْتَانَهُ لِلَّهِ فَاشْتَرَى النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ لَهُ نَخِيلَ الجَنَّةِ. رَبِحَ البَيْعُ. فَرَضِيَ اللهُ عَنْ أَبِي الدَّحْدَاحِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abududahdah_6.mp3"

echo "Generating: assets/audio/khabbab_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>خَبَّابُ بْنُ الأَرَتِّ. الَّذِي جَعَلَ الجَمْرَ فِرَاشَهُ وَلَمْ يَرْتَدَّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/khabbab_0.mp3"

echo "Generating: assets/audio/khabbab_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>كَانَ خَبَّابُ بْنُ الأَرَتِّ عَبْدًا مَمْلُوكًا مِنَ السَّابِقِينَ الأَوَّلِينَ إِلَى الإِسْلَامِ. كَانَ حَدَّادًا يَصْنَعُ السُّيُوفَ لِقُرَيْشٍ. فَلَمَّا أَسْلَمَ صَارَ أَشَدَّ النَّاسِ تَعْذِيبًا فِي مَكَّةَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/khabbab_1.mp3"

echo "Generating: assets/audio/khabbab_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>كَانَتْ سَيِّدَتُهُ تُوقِدُ النَّارَ وَتُلْصِقُ الجَمْرَ بِظَهْرِهِ حَتَّى يَرْتَدَّ عَنِ الإِسْلَامِ. وَمَا أَطْفَأَهَا إِلَّا دَهَنُ ظَهْرِهِ. وَلَمْ يَرْتَدَّ خَبَّابٌ قَطُّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/khabbab_2.mp3"

echo "Generating: assets/audio/khabbab_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ لِخَبَّابٍ: وَاللهِ لَيُتِمَّنَّ هَذَا الأَمْرَ حَتَّى يَسِيرَ الرَّاكِبُ مِنْ صَنْعَاءَ إِلَى حَضْرَمَوْتَ لَا يَخَافُ إِلَّا اللهَ. وَعَدَهُ بِالنَّصْرِ وَحَثَّهُ عَلَى الصَّبْرِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/khabbab_3.mp3"

echo "Generating: assets/audio/khabbab_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>عَاشَ خَبَّابٌ حَتَّى رَأَى النَّصْرَ يَتَحَقَّقُ. وَعِنْدَمَا زَارَهُ الصَّحَابَةُ فِي مَرَضِهِ كَشَفَ لَهُمْ عَنْ ظَهْرِهِ وَقَالَ: انْظُرُوا مَا فَعَلَتِ النَّارُ بِظَهْرِي.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/khabbab_4.mp3"

echo "Generating: assets/audio/khabbab_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ خَبَّابٍ: الثَّبَاتُ عَلَى الحَقِّ فَقَدِ اخْتَارَ أَلَمَ الجَمْرِ عَلَى لَذَّةِ الرِّدَّةِ. وَوَعْدُ اللهِ آتٍ فَقَدْ صَبَرَ وَرَأَى الإِسْلَامَ يَنْتَشِرُ. وَشَرَفُ السَّبْقِ فَكَانَ سَادِسَ مَنْ أَسْلَمَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/khabbab_5.mp3"

echo "Generating: assets/audio/khabbab_6.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مَاتَ خَبَّابٌ وَعَلَى ظَهْرِهِ آثَارُ الجَمْرِ، شَوَاهِدُ لَا تَكْذِبُ عَلَى صِدْقٍ لَا يُوصَفُ. فَرَضِيَ اللهُ عَنْ خَبَّابِ بْنِ الأَرَتِّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/khabbab_6.mp3"

echo "Generating: assets/audio/abbad_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>عَبَّادُ بْنُ بِشْرٍ. الَّذِي كَانَتِ الصَّلَاةُ أَحَبَّ إِلَيْهِ مِنْ حَيَاتِهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abbad_0.mp3"

echo "Generating: assets/audio/abbad_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>صَحَابِيٌّ أَنْصَارِيٌّ مِنَ الأَوْسِ، آمَنَ مُبَكِّرًا وَأَحَبَّ الصَّلَاةَ حُبًّا لَا يُضَاهِيهِ شَيْءٌ. وُصِفَ بِأَنَّهُ كَانَ إِذَا قَامَ يُصَلِّي تَغَيَّرَ وَجْهُهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abbad_1.mp3"

echo "Generating: assets/audio/abbad_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>فِي إِحْدَى سَرَايَا النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، تَنَاوَبَ عَبَّادٌ وَعَمَّارُ بْنُ يَاسِرٍ الحِرَاسَةَ لَيْلًا. فَقَامَ عَبَّادٌ يُصَلِّي فَرَمَاهُ الْعَدُوُّ بِسَهْمٍ، فَنَزَعَهُ وَاصْطَبَرَ وَوَاصَلَ صَلَاتَهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abbad_2.mp3"

echo "Generating: assets/audio/abbad_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ عَبَّادٌ: كُنْتُ فِي سُورَةٍ أَقْرَؤُهَا فَلَمْ أُحِبَّ أَنْ أَقْطَعَهَا. وَلَوْلَا أَنْ أُضَيِّعَ ثَغْرًا أَمَرَنِي رَسُولُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ بِحِفْظِهِ، لَآثَرْتُ أَنْ أُقْتَلَ دُونَ أَنْ أَقْطَعَهَا.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abbad_3.mp3"

echo "Generating: assets/audio/abbad_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ عَبَّادٍ: حَلَاوَةُ الصَّلَاةِ الحَقِيقِيَّةِ تَجْعَلُ صَاحِبَهَا يَنْسَى الأَلَمَ. وَالأَمَانَةُ فِي المَهَمَّةِ فَلَمْ يَتْرُكِ الثَّغْرَ. وَمَرَاتِبُ المُحِبِّينَ، مَنْ أَحَبَّ اللهَ آثَرَ لِقَاءَهُ عَلَى الحَيَاةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abbad_4.mp3"

echo "Generating: assets/audio/abbad_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>ثَلَاثَةُ سِهَامٍ فِي جِسَدِهِ وَهُوَ لَا يَزَالُ يَتْلُو. هَذَا هُوَ عَبَّادُ بْنُ بِشْرٍ. فَرَضِيَ اللهُ عَنْهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abbad_5.mp3"

echo "Generating: assets/audio/umm_amara_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أُمُّ عَمَّارَةَ نُسَيْبَةُ بِنْتُ كَعْبٍ. الْمَرْأَةُ الَّتِي مَدَحَهَا النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ فِي مَيْدَانِ المَعْرَكَةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/umm_amara_0.mp3"

echo "Generating: assets/audio/umm_amara_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أَنْصَارِيَّةٌ مِنَ الخَزْرَجِ، بَايَعَتْ بَيْعَةَ العَقَبَةِ الثَّانِيَةَ. خَرَجَتْ إِلَى غَزْوَةِ أُحُدٍ تَسْقِي الْمُقَاتِلِينَ وَتُدَاوِي الجَرْحَى.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/umm_amara_1.mp3"

echo "Generating: assets/audio/umm_amara_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>لَمَّا انْكَشَفَ الْمُسْلِمُونَ يَوْمَ أُحُدٍ تَحَوَّلَتْ أُمُّ عَمَّارَةَ مِنْ مُمَرِّضَةٍ إِلَى مُقَاتِلَةٍ. أَخَذَتِ السَّيْفَ وَالْقَوْسَ وَالتَّرْسَ وَوَقَفَتْ تَذُبُّ عَنِ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/umm_amara_2.mp3"

echo "Generating: assets/audio/umm_amara_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: مَا الْتَفَتُّ يَمِينًا وَلَا شِمَالًا يَوْمَ أُحُدٍ إِلَّا وَأَنَا أَرَاهَا تُقَاتِلُ دُونِي. وَلَمَّا ضَرَبَ ابْنُ قَمِئَةَ عُنُقَهَا ضَرَبَتْهُ حَتَّى أَعْجَزَتْهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/umm_amara_3.mp3"

echo "Generating: assets/audio/umm_amara_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ أُمِّ عَمَّارَةَ: الْمَرْأَةُ فِي الإِسْلَامِ شَرِيكَةُ الْبِنَاءِ لَا مُتَفَرِّجَةً. وَالطَّوَارِئُ تَكْشِفُ مَعَادِنَ النُّفُوسِ، فَقَدْ جَاءَتْ لِتَسْقِيَ وَبَقِيَتْ لِتُقَاتِلَ. وَمَدِيحُ النَّبِيِّ وَسَامٌ لَا يَعْدِلُهُ شَيْءٌ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/umm_amara_4.mp3"

echo "Generating: assets/audio/umm_amara_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>اثْنَتَا عَشْرَةَ جُرْحًا وَشَهَادَةُ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ. هَذَا مِيرَاثُ نُسَيْبَةَ لِكُلِّ مُسْلِمَةٍ. فَرَضِيَ اللهُ عَنْ أُمِّ عَمَّارَةَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/umm_amara_5.mp3"

echo "Generating: assets/audio/abu_aqeel_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أَبُو عَقِيلٍ الأَنْصَارِيُّ. الَّذِي أَنْزَلَ اللهُ فِيهِ آيَةً تُتْلَى إِلَى يَوْمِ القِيَامَةِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_aqeel_0.mp3"

echo "Generating: assets/audio/abu_aqeel_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>صَحَابِيٌّ أَنْصَارِيٌّ فَقِيرٌ. لَمَّا نَادَى النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ إِلَى الصَّدَقَةِ لِتَجْهِيزِ جَيْشِ العُسْرَةِ، آجَرَ نَفْسَهُ لَيْلَةً كَامِلَةً بِصَاعَيْنِ مِنَ التَّمْرِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_aqeel_1.mp3"

echo "Generating: assets/audio/abu_aqeel_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>جَاءَ أَبُو عَقِيلٍ بِنِصْفِ الصَّاعَيْنِ صَدَقَةً وَاحْتَبَسَ النِّصْفَ الآخَرَ لِأَهْلِهِ. فَسَخِرَ الْمُنَافِقُونَ وَقَالُوا: إِنَّ اللهَ لَغَنِيٌّ عَنْ صَدَقَةِ هَذَا.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_aqeel_2.mp3"

echo "Generating: assets/audio/abu_aqeel_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>نَزَلَ الْقُرْآنُ يَرُدُّ عَلَى الْمُنَافِقِينَ: الَّذِينَ يَلْمِزُونَ الْمُطَّوِّعِينَ مِنَ الْمُؤْمِنِينَ فِي الصَّدَقَاتِ وَالَّذِينَ لَا يَجِدُونَ إِلَّا جُهْدَهُمْ فَيَسْخَرُونَ مِنْهُمْ، سَخِرَ اللهُ مِنْهُمْ وَلَهُمْ عَذَابٌ أَلِيمٌ. سُورَةُ التَّوْبَةِ آيَةُ تِسْعَةٍ وَسَبْعِينَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_aqeel_3.mp3"

echo "Generating: assets/audio/abu_aqeel_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ أَبِي عَقِيلٍ: لَا صَغِيرَةَ فِي مِيزَانِ الإِخْلَاصِ، فَنِصْفُ صَاعٍ بِنِيَّةٍ صَادِقَةٍ يَسْتَحِقُّ آيَةً قُرْآنِيَّةً. وَالسُّخْرِيَةُ مِنَ العَطَاءِ سِلَاحُ الخَائِفِينَ. وَالْفَقِيرُ الْمُعْطِي أَغْنَى مِنَ الغَنِيِّ الشَّاهِدِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_aqeel_4.mp3"

echo "Generating: assets/audio/abu_aqeel_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>نِصْفُ صَاعٍ تَعِبَ فِيهِ لَيْلَةً صَارَ آيَةً خَالِدَةً فِي كِتَابِ اللهِ. فَرَضِيَ اللهُ عَنْ أَبِي عَقِيلٍ الأَنْصَارِيِّ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_aqeel_5.mp3"

echo "Generating: assets/audio/ubada_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>عُبَادَةُ بْنُ الصَّامِتِ. أَوَّلُ مَنْ حَمَلَ الْقُرْآنَ إِلَى الشَّامِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/ubada_0.mp3"

echo "Generating: assets/audio/ubada_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ سَادَاتِ الْخَزْرَجِ، كَانَ نَقِيبًا فِي بَيْعَةِ الْعَقَبَةِ الثَّانِيَةِ الَّتِي أَسَّسَتْ لِلْهِجْرَةِ. كَانَ طَوِيلًا أَسْوَدَ جَلِيلَ الْمَنْظَرِ، إِذَا رَآهُ النَّاسُ هَابُوهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/ubada_1.mp3"

echo "Generating: assets/audio/ubada_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أَرْسَلَهُ عُمَرُ بْنُ الْخَطَّابِ رَضِيَ اللهُ عَنْهُ مُعَلِّمًا إِلَى الشَّامِ. فَانْتَشَرَ عُبَادَةُ فِي الشَّامِ حَتَّى صَارَ كُلُّ مَنْ تَعَلَّمَ الْقُرْآنَ فِيهَا يَعُودُ بِنَسَبِهِ إِلَيْهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/ubada_2.mp3"

echo "Generating: assets/audio/ubada_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>وَقَفَ عُبَادَةُ أَمَامَ مُعَاوِيَةَ بِلَا مُهَادَنَةٍ حِينَ رَأَى مُنْكَرًا وَقَالَ: لَا أُبَالِي بِسَخَطِكَ إِذَا كُنْتُ فِي رِضَا اللهِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/ubada_3.mp3"

echo "Generating: assets/audio/ubada_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ عُبَادَةَ: حَامِلُ الْقُرْآنِ رِسَالَتُهُ لَا تَنْتَهِي بِمَوْتِهِ. وَالنَّقِيبُ الْحَقِيقِيُّ يَقُودُ بِالْعِلْمِ فَقَدْ فَتَحَ عُبَادَةُ الشَّامَ بِالْقُرْآنِ. وَالشَّجَاعَةُ كَلِمَةُ حَقٍّ عِنْدَ سُلْطَانٍ جَائِرٍ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/ubada_4.mp3"

echo "Generating: assets/audio/ubada_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>رَحَلَ عُبَادَةُ وَخَلَّفَ أَجْيَالًا مِنْ حُفَّاظِ الشَّامِ. وَهُمْ فِي مِيزَانِهِ إِلَى يَوْمِ الدِّينِ. فَرَضِيَ اللهُ عَنْ عُبَادَةَ بْنِ الصَّامِتِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/ubada_5.mp3"

echo "Generating: assets/audio/abu_darda_0.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أَبُو الدَّرْدَاءِ عُوَيْمِرُ بْنُ زَيْدٍ. التَّاجِرُ الَّذِي تَرَكَ السُّوقَ لِيَفْتَحَ مَدَارِسَ الْعِلْمِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_darda_0.mp3"

echo "Generating: assets/audio/abu_darda_1.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>أَسْلَمَ أَبُو الدَّرْدَاءِ مُتَأَخِّرًا عَنِ الْبَدْرِيِّينَ وَكَانَ تَاجِرًا مَشْغُولًا. فَلَمَّا أَسْلَمَ رَأَى أَنَّ التِّجَارَةَ وَالْعِلْمَ لَا يَجْتَمِعَانِ فَاخْتَارَ الْعِلْمَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_darda_1.mp3"

echo "Generating: assets/audio/abu_darda_2.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>قَالَ سَلْمَانُ لِأَبِي الدَّرْدَاءِ: إِنَّ لِرَبِّكَ عَلَيْكَ حَقًّا وَلِنَفْسِكَ عَلَيْكَ حَقًّا وَلِأَهْلِكَ عَلَيْكَ حَقًّا فَأَعْطِ كُلَّ ذِي حَقٍّ حَقَّهُ. فَقَالَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: صَدَقَ سَلْمَانُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_darda_2.mp3"

echo "Generating: assets/audio/abu_darda_3.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>صَارَ أَبُو الدَّرْدَاءِ قَاضِيَ دِمَشْقَ وَمُعَلِّمَهَا. وَكَانَ يَجْلِسُ إِلَيْهِ أَلْفٌ وَسِتُّمِئَةِ طَالِبٍ. وَكَانَ يَقُولُ: تَعَلَّمُوا الْعِلْمَ قَبْلَ أَنْ يُرْفَعَ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_darda_3.mp3"

echo "Generating: assets/audio/abu_darda_4.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>مِنْ دُرُوسِ أَبِي الدَّرْدَاءِ: التَّحَوُّلُ الْكَامِلُ لِلَّهِ فَقَدْ تَرَكَ التِّجَارَةَ لِأَنَّ الْعِلْمَ أَعْلَى. وَالتَّوَازُنُ الإِسْلَامِيُّ فَالزُّهْدُ لَا يُلْغِي الْوَاجِبَاتِ. وَأَثَرُ الْعَالِمِ أَلْفٌ وَسِتُّمِئَةِ طَالِبٍ يَحْمِلُونَ عِلْمَهُ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_darda_4.mp3"

echo "Generating: assets/audio/abu_darda_5.mp3"
curl -s -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -H "Content-Type: application/json" -d '{"input":{"ssml":"<speak>تَرَكَ أَبُو الدَّرْدَاءِ السُّوقَ وَلَمْ يَنْدَمْ. وَتَرَكَ عِلْمًا يُضِيءُ الشَّامَ حَتَّى الْيَوْمِ. فَرَضِيَ اللهُ عَنْ أَبِي الدَّرْدَاءِ.</speak>"},"voice":{"languageCode":"ar-XA","name":"ar-XA-Wavenet-D"},"audioConfig":{"audioEncoding":"MP3","speakingRate":0.9}}' "https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' | base64 --decode > "C:/Users/melwa/OneDrive/Documents/GitHub/shadow_islamic_heroes/assets/audio/abu_darda_5.mp3"
